name: Initialize Node.js, pnpm, and dependencies
description: Base for most of workflows
inputs:
  cache:
    required: false
    default: 'pnpm'
    description: Allow to disable pnpm cache for better security
  install:
    required: false
    default: ''
    description: Allow to disable `pnpm install` call
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v3
      with:
        node-version-file: .node-version
        cache: ${{ inputs.cache && 'pnpm' || '' }}
    - if: ${{ inputs.install != 'false' }}
      shell: bash
      run: pnpm install ${{ inputs.install }}
